name: Generate Snake Game

on:
  # Run automatically every 12 hours
  schedule:
    - cron: "0 */12 * * *"

  # Allow manual trigger
  workflow_dispatch:

  # Run on every push to main branch
  push:
    branches: [main, master]

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      # Checkout repository content
      - name: Checkout
        uses: actions/checkout@v3

      # Generate snake game from contribution graph
      - name: Generate Snake Game
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: wahyudivaaa
          outputs: |
            dist/snake.svg
            dist/snake-dark.svg?palette=github-dark
            dist/snake.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9

      # Push generated files to output branch
      - name: Push Snake Game to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
